# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: Docusaurus

on:
  push:
    branches:
      - main

jobs:
  build-compiler-explorer:
    name: Build Compiler Explorer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0 # We hit an LLVM error building Wasm on 1.72
          override: true
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: "Build Compiler Playground Wasm NPM package"
        run: RUST_LOG=debug wasm-pack build --target web
        working-directory: ./compiler/crates/relay-compiler-playground
      - uses: actions/upload-artifact@v3
        with:
          name: compiler-playground-package
          path: compiler/crates/relay-compiler-playground/pkg/

  build-cargo-docs:
    name: Build cargo docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.0
          override: true
      - name: "Build cargo docs"
        run: |
          cargo doc --manifest-path=compiler/Cargo.toml --locked --features vendored
          zip cargo-docs.zip compiler/target/doc

      - uses: actions/upload-artifact@v3
        with:
          name: compiler-cargo-docs
          path: cargo-docs.zip

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [build-compiler-explorer, build-cargo-docs]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Download Compiler Explorer
        uses: actions/download-artifact@v2
        with:
          name: compiler-playground-package
          path: tmp/compiler-playground-package

      - name: Link Compiler Explorer
        run: yarn link
        working-directory: tmp/compiler-playground-package

      - name: Install and Build
        run: |
          yarn
          yarn link relay-compiler-playground
          yarn build
        working-directory: website/

      - name: Download Cargo docs
        uses: actions/download-artifact@v2
        with:
          name: compiler-cargo-docs
          path: tmp/cargo-docs.zip

      - name: Install cargo docs
        run: |
          unzip tmp/cargo-docs.zip
          mv -r docs build/cargo-docs
        working-directory: website

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/build
          CLEAN: true
